In [14]:
import pandas as pd
import numpy as np

df = pd.read_excel("C:/Users/mansi desai/Desktop/dailyActivity_merged.xlsx")
df.head(31)

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-12-04 00:00:00,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863
5,1503960366,4/17/2016,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728
6,1503960366,4/18/2016,13019,8.59,8.59,0.0,3.25,0.64,4.71,0.0,42,16,233,1149,1921
7,1503960366,4/19/2016,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.0,50,31,264,775,2035
8,1503960366,4/20/2016,10544,6.68,6.68,0.0,1.96,0.48,4.24,0.0,28,12,205,818,1786
9,1503960366,4/21/2016,9819,6.34,6.34,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775
10,1503960366,4/22/2016,12764,8.13,8.13,0.0,4.76,1.12,2.24,0.0,66,27,130,1217,1827
11,1503960366,4/23/2016,14371,9.04,9.04,0.0,2.81,0.87,5.36,0.0,41,21,262,732,1949
12,1503960366,4/24/2016,10039,6.41,6.41,0.0,2.92,0.21,3.28,0.0,39,5,238,709,1788
13,1503960366,4/25/2016,15355,9.80,9.80,0.0,5.29,0.57,3.94,0.0,73,14,216,814,2013
14,1503960366,4/26/2016,13755,8.79,8.79,0.0,2.33,0.92,5.54,0.0,31,23,279,833,1970
15,1503960366,4/27/2016,18134,12.21,12.21,0.0,6.40,0.41,5.41,0.0,78,11,243,1108,2159
16,1503960366,4/28/2016,13154,8.53,8.53,0.0,3.54,1.16,3.79,0.0,48,28,189,782,1898
17,1503960366,4/29/2016,11181,7.15,7.15,0.0,1.06,0.50,5.58,0.0,16,12,243,815,1837
18,1503960366,4/30/2016,14673,9.25,9.25,0.0,3.56,1.42,4.27,0.0,52,34,217,712,1947
19,1503960366,2016-01-05 00:00:00,10602,6.81,6.81,0.0,2.29,1.60,2.92,0.0,33,35,246,730,1820
20,1503960366,2016-02-05 00:00:00,14727,9.71,9.71,0.0,3.21,0.57,5.92,0.0,41,15,277,798,2004
21,1503960366,2016-03-05 00:00:00,15103,9.66,9.66,0.0,3.73,1.05,4.88,0.0,50,24,254,816,1990
22,1503960366,2016-04-05 00:00:00,11100,7.15,7.15,0.0,2.46,0.87,3.82,0.0,36,22,203,1179,1819
23,1503960366,2016-05-05 00:00:00,14070,8.90,8.90,0.0,2.92,1.08,4.88,0.0,45,24,250,857,1959
24,1503960366,2016-06-05 00:00:00,12159,8.03,8.03,0.0,1.97,0.25,5.81,0.0,24,6,289,754,1896
25,1503960366,2016-07-05 00:00:00,11992,7.71,7.71,0.0,2.46,2.12,3.13,0.0,37,46,175,833,1821
26,1503960366,2016-08-05 00:00:00,10060,6.58,6.58,0.0,3.53,0.32,2.73,0.0,44,8,203,574,1740
27,1503960366,2016-09-05 00:00:00,12022,7.72,7.72,0.0,3.45,0.53,3.74,0.0,46,11,206,835,1819
28,1503960366,2016-10-05 00:00:00,12207,7.77,7.77,0.0,3.35,1.16,3.26,0.0,46,31,214,746,1859
29,1503960366,2016-11-05 00:00:00,12770,8.13,8.13,0.0,2.56,1.01,4.55,0.0,36,23,251,669,1783
30,1503960366,2016-12-05 00:00:00,0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0,0,0,1440,0

In [7]:
df.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [15]:
# combining all the same domain column for ease...

# Minutes
df['TotalMinutes'] = df["VeryActiveMinutes"] + df["FairlyActiveMinutes"] + df["LightlyActiveMinutes"] + df["SedentaryMinutes"]
print(df["TotalMinutes"].head(31))
df.head(31)

# Distance

0     1094
1     1033
2     1440
3      998
4     1040
5      761
6     1440
7     1120
8     1063
9     1076
10    1440
11    1056
12     991
13    1117
14    1166
15    1440
16    1047
17    1086
18    1015
19    1044
20    1131
21    1144
22    1440
23    1176
24    1073
25    1091
26     829
27    1098
28    1037
29     979
30    1440
Name: TotalMinutes, dtype: int64

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,TotalMinutes
0,1503960366,2016-12-04 00:00:00,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,1094
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,1033
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,1440
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,998
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,1040
5,1503960366,4/17/2016,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728,761
6,1503960366,4/18/2016,13019,8.59,8.59,0.0,3.25,0.64,4.71,0.0,42,16,233,1149,1921,1440
7,1503960366,4/19/2016,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.0,50,31,264,775,2035,1120
8,1503960366,4/20/2016,10544,6.68,6.68,0.0,1.96,0.48,4.24,0.0,28,12,205,818,1786,1063
9,1503960366,4/21/2016,9819,6.34,6.34,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775,1076
10,1503960366,4/22/2016,12764,8.13,8.13,0.0,4.76,1.12,2.24,0.0,66,27,130,1217,1827,1440
11,1503960366,4/23/2016,14371,9.04,9.04,0.0,2.81,0.87,5.36,0.0,41,21,262,732,1949,1056
12,1503960366,4/24/2016,10039,6.41,6.41,0.0,2.92,0.21,3.28,0.0,39,5,238,709,1788,991
13,1503960366,4/25/2016,15355,9.80,9.80,0.0,5.29,0.57,3.94,0.0,73,14,216,814,2013,1117
14,1503960366,4/26/2016,13755,8.79,8.79,0.0,2.33,0.92,5.54,0.0,31,23,279,833,1970,1166
15,1503960366,4/27/2016,18134,12.21,12.21,0.0,6.40,0.41,5.41,0.0,78,11,243,1108,2159,1440
16,1503960366,4/28/2016,13154,8.53,8.53,0.0,3.54,1.16,3.79,0.0,48,28,189,782,1898,1047
17,1503960366,4/29/2016,11181,7.15,7.15,0.0,1.06,0.50,5.58,0.0,16,12,243,815,1837,1086
18,1503960366,4/30/2016,14673,9.25,9.25,0.0,3.56,1.42,4.27,0.0,52,34,217,712,1947,1015
19,1503960366,2016-01-05 00:00:00,10602,6.81,6.81,0.0,2.29,1.60,2.92,0.0,33,35,246,730,1820,1044
20,1503960366,2016-02-05 00:00:00,14727,9.71,9.71,0.0,3.21,0.57,5.92,0.0,41,15,277,798,2004,1131
21,1503960366,2016-03-05 00:00:00,15103,9.66,9.66,0.0,3.73,1.05,4.88,0.0,50,24,254,816,1990,1144
22,1503960366,2016-04-05 00:00:00,11100,7.15,7.15,0.0,2.46,0.87,3.82,0.0,36,22,203,1179,1819,1440
23,1503960366,2016-05-05 00:00:00,14070,8.90,8.90,0.0,2.92,1.08,4.88,0.0,45,24,250,857,1959,1176
24,1503960366,2016-06-05 00:00:00,12159,8.03,8.03,0.0,1.97,0.25,5.81,0.0,24,6,289,754,1896,1073
25,1503960366,2016-07-05 00:00:00,11992,7.71,7.71,0.0,2.46,2.12,3.13,0.0,37,46,175,833,1821,1091
26,1503960366,2016-08-05 00:00:00,10060,6.58,6.58,0.0,3.53,0.32,2.73,0.0,44,8,203,574,1740,829
27,1503960366,2016-09-05 00:00:00,12022,7.72,7.72,0.0,3.45,0.53,3.74,0.0,46,11,206,835,1819,1098
28,1503960366,2016-10-05 00:00:00,12207,7.77,7.77,0.0,3.35,1.16,3.26,0.0,46,31,214,746,1859,1037
29,1503960366,2016-11-05 00:00:00,12770,8.13,8.13,0.0,2.56,1.01,4.55,0.0,36,23,251,669,1783,979
30,1503960366,2016-12-05 00:00:00,0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0,0,0,1440,0,1440

In [18]:
df["ActivityDate"] = pd.to_datetime(df["ActivityDate"],format = "%m%d%y")
print(df.info)

ValueError: time data '2016-12-04 00:00:00' does not match format '%m%d%y' (match)